# -*- coding: utf-8 -*-
"""AlunoMédia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PuByqx1mUMtx9e3TzuvKKd8Rcs9V4YZ_
"""

nota1 = float(input('Nota 1:'))

nota2 = float(input('Nota 2:')) 

nota3 = float(input('Nota 3:')) 

media = (nota1 + nota2 + nota3) / 3

if media >= 7:
    sit = 'aprovado'
elif media >= 4:
    sit = 'recuperação'
else:
    sit = 'reprovado'
print(f'o aluno está {sit} com média {media:.2f}')